---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  # @see https://github.com/someara/dokken-images
  # @see https://hub.docker.com/r/dokken/
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      privileged: true
      pid_one_command: /bin/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
        - /sys/fs/selinux:/sys/fs/selinux:ro # required by systemd
suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

